# Generated by Django 4.2 on 2025-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertask',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathertask',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
