# Generated by Django 4.2 on 2025-10-10 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_weathertask_is_automatic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название правила (например: 'Жара и влажность')", max_length=100)),
                ('condition_type', models.CharField(choices=[('temperature', 'Температура'), ('humidity', 'Влажность'), ('rain_probability', 'Вероятность дождя'), ('wind_speed', 'Скорость ветра')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', 'больше'), ('gte', 'больше или равно'), ('lt', 'меньше'), ('lte', 'меньше или равно'), ('eq', 'равно')], max_length=10)),
                ('threshold_value', models.FloatField(help_text='Пороговое значение')),
                ('task_description', models.TextField(help_text='Описание задачи при срабатывании')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Правило погоды',
                'verbose_name_plural': 'Правила погоды',
            },
        ),
    ]
