# Generated by Django 5.2.7 on 2025-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_weatherrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrule',
            options={},
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='task_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='threshold_value',
            field=models.FloatField(),
        ),
    ]
