# Generated by Django 5.2.7 on 2025-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_weatherrule_options_alter_weatherrule_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrule',
            options={'verbose_name': 'Правило погоды', 'verbose_name_plural': 'Правила погоды'},
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='name',
            field=models.CharField(help_text="Название правила (например: 'Жара и влажность')", max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='task_description',
            field=models.TextField(help_text='Описание задачи при срабатывании'),
        ),
        migrations.AlterField(
            model_name='weatherrule',
            name='threshold_value',
            field=models.FloatField(help_text='Пороговое значение'),
        ),
    ]
