# Generated by Django 5.2.7 on 2025-10-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_weatherrule_options_alter_weatherrule_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrule',
            options={'verbose_name': 'Правило погоды', 'verbose_name_plural': 'Правила погоды'},
        ),
    ]
