# Generated by Django 6.0a1 on 2025-10-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название города')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('weather_data', models.JSONField(default=dict, verbose_name='Данные погоды')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='Время кэширования')),
            ],
            options={
                'verbose_name': 'Кэш погоды',
                'verbose_name_plural': 'Кэш погоды',
                'indexes': [models.Index(fields=['city_name'], name='dashboard_w_city_na_47ce67_idx'), models.Index(fields=['cached_at'], name='dashboard_w_cached__2c77d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CitySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Название города')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', 'searched_at'], name='dashboard_c_user_id_4db084_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('rain', '🌧️ Дождь'), ('cold', '🥶 Холод'), ('hot', '🔥 Жара'), ('wind', '💨 Ветер'), ('snow', '❄️ Снег'), ('general', '📝 Общее')], default='general', max_length=20, verbose_name='Тип задачи')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Погодная задача',
                'verbose_name_plural': 'Погодные задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='dashboard_w_user_id_57940a_idx'), models.Index(fields=['created_at'], name='dashboard_w_created_c25ad3_idx')],
            },
        ),
    ]
