# Generated by Django 6.0a1 on 2025-10-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weathercache',
            name='dashboard_w_city_na_47ce67_idx',
        ),
        migrations.RemoveIndex(
            model_name='weathercache',
            name='dashboard_w_cached__2c77d6_idx',
        ),
        migrations.DeleteModel(
            name='WeatherCache',
        ),
        migrations.AlterModelOptions(
            name='citysearchhistory',
            options={'verbose_name': 'История поиска', 'verbose_name_plural': 'Истории поиска'},
        ),
        migrations.AlterModelOptions(
            name='weathertask',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveIndex(
            model_name='citysearchhistory',
            name='dashboard_c_user_id_4db084_idx',
        ),
        migrations.RemoveIndex(
            model_name='weathertask',
            name='dashboard_w_user_id_57940a_idx',
        ),
        migrations.RemoveIndex(
            model_name='weathertask',
            name='dashboard_w_created_c25ad3_idx',
        ),
        migrations.AddField(
            model_name='weathertask',
            name='related_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Связанный город'),
        ),
        migrations.AlterField(
            model_name='citysearchhistory',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='citysearchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='citysearchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weathertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='weathertask',
            name='city',
        ),
        migrations.RemoveField(
            model_name='weathertask',
            name='task_type',
        ),
    ]
