# Generated by Django 4.2.7 on 2025-09-26 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('description', models.CharField(max_length=200, verbose_name='Описание погоды')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('pressure', models.IntegerField(verbose_name='Давление')),
                ('cached_at', models.DateTimeField(auto_now_add=True, verbose_name='Время кэширования')),
            ],
            options={
                'verbose_name': 'Кэш погоды',
                'verbose_name_plural': 'Кэш погоды',
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-searched_at'],
                'unique_together': {('user', 'city')},
            },
        ),
    ]
