# Generated by Django 5.2.7 on 2025-10-09 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок заметки')),
                ('content', models.TextField(verbose_name='Содержание заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка пользователя',
                'verbose_name_plural': 'Заметки пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скорость ветра')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Данные погоды',
                'verbose_name_plural': 'Данные погоды',
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
