# Generated by Django 5.2.6 on 2025-10-13 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_theme_favoritecity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('weather_data', models.JSONField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
