import { useState, useEffect } from 'react';
import { 
  Search, CloudRain, Sun, Cloud, Wind, Droplets, 
  Plus, X, Check, Loader2, Clock, MapPin 
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function App() {
  const [searchCity, setSearchCity] = useState('');
  const [weather, setWeather] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [searchHistory, setSearchHistory] = useState([]);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [newTask, setNewTask] = useState('');
  const [editingTask, setEditingTask] = useState(null);

  // Mock data for demonstration
  const weatherConditions = {
    Clear: { icon: Sun, color: 'text-yellow-400', bg: 'bg-yellow-50' },
    Clouds: { icon: Cloud, color: 'text-gray-500', bg: 'bg-gray-50' },
    Rain: { icon: CloudRain, color: 'text-blue-500', bg: 'bg-blue-50' },
    Drizzle: { icon: CloudRain, color: 'text-blue-300', bg: 'bg-blue-50' },
    Thunderstorm: { icon: Cloud, color: 'text-purple-600', bg: 'bg-purple-50' },
    Snow: { icon: Cloud, color: 'text-cyan-300', bg: 'bg-cyan-50' },
    Mist: { icon: Cloud, color: 'text-indigo-300', bg: 'bg-indigo-50' }
  };

  const mockWeatherData = (city) => {
    const temp = Math.floor(Math.random() * 30) - 5;
    const humidity = Math.floor(Math.random() * 100);
    const conditionKeys = Object.keys(weatherConditions);
    const condition = conditionKeys[Math.floor(Math.random() * conditionKeys.length)];
    
    return {
      city,
      temperature: temp,
      humidity,
      condition,
      icon: weatherConditions[condition].icon,
      lastUpdated: new Date().toISOString()
    };
  };

  const handleSearch = async () => {
    if (!searchCity.trim()) return;
    
    setIsLoading(true);
    setError(null);
    
    try {
      // Simulate API delay and errors
      await new Promise(resolve => setTimeout(resolve, 800));
      
      if (searchCity.toLowerCase() === 'error') {
        throw new Error('API_ERROR');
      }
      
      if (searchCity.toLowerCase() === 'notfound') {
        throw new Error('CITY_NOT_FOUND');
      }
      
      const weatherData = mockWeatherData(searchCity);
      setWeather(weatherData);
      
      // Update search history (max 5 items)
      setSearchHistory(prev => {
        const newHistory = [searchCity, ...prev.filter(city => city !== searchCity)];
        return newHistory.slice(0, 5);
      });
      
      // Auto-create weather-based task
      if (weatherData.condition === 'Rain' && !tasks.some(t => t.city === searchCity && t.autoGenerated)) {
        setTasks(prev => [...prev, {
          id: Date.now(),
          city: searchCity,
          description: 'Взять зонт',
          completed: false,
          autoGenerated: true
        }]);
      }
    } catch (err) {
      if (err.message === 'CITY_NOT_FOUND') {
        setError('Город не найден. Проверьте название и попробуйте снова.');
      } else if (err.message === 'API_ERROR') {
        setError('Превышен лимит запросов. Попробуйте через 10 минут.');
      } else {
        setError('Сервис погоды временно недоступен. Пожалуйста, попробуйте позже.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddTask = () => {
    if (!newTask.trim() || !weather) return;
    
    setTasks(prev => [...prev, {
      id: Date.now(),
      city: weather.city,
      description: newTask,
      completed: false,
      autoGenerated: false
    }]);
    
    setNewTask('');
  };

  const handleToggleTask = (id) => {
    setTasks(prev => prev.map(task => 
      task.id === id ? { ...task, completed: !task.completed } : task
    ));
  };

  const handleDeleteTask = (id) => {
    setTasks(prev => prev.filter(task => task.id !== id));
  };

  const handleEditTask = (task) => {
    setEditingTask(task);
    setNewTask(task.description);
  };

  const handleUpdateTask = () => {
    if (!newTask.trim() || !editingTask) return;
    
    setTasks(prev => prev.map(task => 
      task.id === editingTask.id ? { ...task, description: newTask } : task
    ));
    
    setEditingTask(null);
    setNewTask('');
  };

  const getConditionStyle = (condition) => {
    const conditionKey = Object.keys(weatherConditions).find(key => 
      condition.toLowerCase().includes(key.toLowerCase())
    ) || 'Clouds';
    
    return weatherConditions[conditionKey];
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="max-w-6xl mx-auto p-4 sm:p-6">
        {/* Header */}
        <header className="text-center mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-700 mb-2">
            WeatherTask Dashboard
          </h1>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Отслеживайте погоду и создавайте задачи, связанные с погодными условиями
          </p>
        </header>

        {/* Search Section */}
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row gap-4 mb-6">
            <div className="relative flex-1">
              <input
                type="text"
                value={searchCity}
                onChange={(e) => setSearchCity(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                placeholder="Введите название города..."
                className="w-full pl-12 pr-4 py-3 rounded-xl border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm transition-all"
              />
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
            </div>
            <button
              onClick={handleSearch}
              disabled={isLoading}
              className="bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-700 hover:to-indigo-800 text-white px-6 py-3 rounded-xl font-medium shadow-lg flex items-center justify-center transition-all disabled:opacity-70 disabled:cursor-not-allowed transform hover:scale-[1.02]"
            >
              {isLoading ? (
                <Loader2 className="animate-spin h-5 w-5 mr-2" />
              ) : (
                <Search className="h-5 w-5 mr-2" />
              )}
              Найти
            </button>
          </div>

          {/* Error Message */}
          <AnimatePresence>
            {error && (
              <motion.div
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl mb-6"
              >
                <div className="flex items-center">
                  <X className="h-5 w-5 mr-2 flex-shrink-0" />
                  <p>{error}</p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Weather Display */}
          {weather && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className={`rounded-2xl p-6 shadow-xl ${getConditionStyle(weather.condition).bg}`}
            >
              <div className="flex flex-col md:flex-row justify-between items-center">
                <div className="text-center md:text-left mb-4 md:mb-0">
                  <div className="flex items-center justify-center md:justify-start mb-2">
                    <MapPin className="h-5 w-5 text-gray-500 mr-2" />
                    <h2 className="text-2xl font-bold text-gray-800">{weather.city}</h2>
                  </div>
                  <p className="text-gray-600 flex items-center justify-center md:justify-start">
                    <Clock className="h-4 w-4 mr-1" />
                    Обновлено: {new Date(weather.lastUpdated).toLocaleTimeString()}
                  </p>
                </div>
                
                <div className="flex items-center">
                  <div className={`p-4 rounded-full ${getConditionStyle(weather.condition).bg}`}>
                    <weather.icon className={`h-16 w-16 ${getConditionStyle(weather.condition).color}`} />
                  </div>
                  <div className="ml-6 text-right">
                    <p className="text-5xl font-bold text-gray-800">{Math.round(weather.temperature)}°C</p>
                    <p className="text-xl text-gray-600 capitalize mt-1">{weather.condition.toLowerCase()}</p>
                  </div>
                </div>
              </div>
              
              <div className="mt-6 flex flex-wrap justify-center md:justify-start gap-4">
                <div className="flex items-center bg-white rounded-lg px-4 py-2 shadow">
                  <Droplets className="h-5 w-5 text-blue-500 mr-2" />
                  <span className="font-medium">Влажность:</span>
                  <span className="ml-2 text-gray-700">{weather.humidity}%</span>
                </div>
                <div className="flex items-center bg-white rounded-lg px-4 py-2 shadow">
                  <Wind className="h-5 w-5 text-gray-500 mr-2" />
                  <span className="font-medium">Ветер:</span>
                  <span className="ml-2 text-gray-700">{Math.floor(Math.random() * 15) + 5} км/ч</span>
                </div>
              </div>
            </motion.div>
          )}
        </div>

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Tasks Section */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-xl p-6 mb-6">
              <div className="flex justify-between items-center mb-5">
                <h2 className="text-xl font-bold text-gray-800 flex items-center">
                  <Plus className="h-5 w-5 mr-2 text-blue-500" />
                  Задачи
                </h2>
              </div>
              
              {/* Task Input */}
              <div className="flex flex-col sm:flex-row gap-3 mb-6">
                <input
                  type="text"
                  value={newTask}
                  onChange={(e) => setNewTask(e.target.value)}
                  placeholder={weather ? `Новая задача для ${weather.city}...` : "Сначала найдите город"}
                  disabled={!weather}
                  className="flex-1 px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-50"
                />
                <button
                  onClick={editingTask ? handleUpdateTask : handleAddTask}
                  disabled={!newTask.trim() || !weather}
                  className={`px-6 py-3 rounded-lg font-medium transition-all ${
                    !newTask.trim() || !weather
                      ? 'bg-gray-200 text-gray-500 cursor-not-allowed'
                      : 'bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white shadow-md'
                  }`}
                >
                  {editingTask ? 'Обновить' : 'Добавить'}
                </button>
              </div>
              
              {/* Tasks List */}
              <div className="space-y-3 max-h-96 overflow-y-auto pr-2">
                <AnimatePresence>
                  {tasks.filter(task => weather && task.city === weather.city).length === 0 ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="text-center py-8 text-gray-500 bg-gray-50 rounded-xl"
                    >
                      <Plus className="h-12 w-12 mx-auto mb-3 opacity-20" />
                      <p>Задачи для этого города отсутствуют</p>
                    </motion.div>
                  ) : (
                    tasks
                      .filter(task => weather && task.city === weather.city)
                      .map(task => (
                        <motion.div
                          key={task.id}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: 20 }}
                          className="flex items-center p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"
                        >
                          <button
                            onClick={() => handleToggleTask(task.id)}
                            className={`w-6 h-6 rounded-full border-2 mr-4 flex-shrink-0 flex items-center justify-center ${
                              task.completed 
                                ? 'bg-green-500 border-green-500' 
                                : 'border-gray-400 hover:border-blue-500'
                            }`}
                          >
                            {task.completed && <Check className="h-4 w-4 text-white" />}
                          </button>
                          
                          <div className="flex-1 min-w-0">
                            <p className={`font-medium ${task.completed ? 'line-through text-gray-500' : 'text-gray-800'}`}>
                              {task.description}
                            </p>
                            {task.autoGenerated && (
                              <span className="inline-block mt-1 bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full">
                                Рекомендация
                              </span>
                            )}
                          </div>
                          
                          <div className="flex space-x-2 ml-4 flex-shrink-0">
                            <button
                              onClick={() => handleEditTask(task)}
                              className="text-blue-500 hover:text-blue-700 p-1"
                            >
                              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                              </svg>
                            </button>
                            <button
                              onClick={() => handleDeleteTask(task.id)}
                              className="text-red-500 hover:text-red-700 p-1"
                            >
                              <X className="h-5 w-5" />
                            </button>
                          </div>
                        </motion.div>
                      ))
                  )}
                </AnimatePresence>
              </div>
            </div>
          </div>
          
          {/* Search History */}
          <div>
            <div className="bg-white rounded-2xl shadow-xl p-6">
              <h2 className="text-xl font-bold text-gray-800 mb-5 flex items-center">
                <Clock className="h-5 w-5 mr-2 text-indigo-500" />
                История поиска
              </h2>
              
              <div className="space-y-3">
                <AnimatePresence>
                  {searchHistory.length === 0 ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="text-center py-8 text-gray-500 bg-gray-50 rounded-xl"
                    >
                      <Clock className="h-12 w-12 mx-auto mb-3 opacity-20" />
                      <p>История поиска пуста</p>
                    </motion.div>
                  ) : (
                    searchHistory.map((city, index) => (
                      <motion.div
                        key={city}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -20 }}
                        className="flex items-center p-3 bg-gray-50 rounded-lg hover:bg-gray-100 cursor-pointer transition-colors"
                        onClick={() => {
                          setSearchCity(city);
                          handleSearch();
                        }}
                      >
                        <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center mr-3 flex-shrink-0">
                          <span className="text-blue-600 font-medium">{index + 1}</span>
                        </div>
                        <span className="font-medium text-gray-700">{city}</span>
                      </motion.div>
                    ))
                  )}
                </AnimatePresence>
              </div>
            </div>
            
            {/* Info Card */}
            <div className="mt-6 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-2xl p-5 text-white shadow-xl">
              <h3 className="text-lg font-bold mb-3 flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Совет
              </h3>
              <p className="text-blue-100">
                Создавайте задачи, связанные с погодными условиями. Например: 
                "Взять зонт", "Проверить кондиционер", "Подготовить теплую одежду".
              </p>
            </div>
          </div>
        </div>
        
        {/* Footer */}
        <footer className="mt-10 text-center text-gray-500 text-sm py-6 border-t border-gray-200">
          <p>WeatherTask Dashboard • Данные обновляются не реже 1 раза в 2 часа</p>
          <p className="mt-1">Используется mock-данные для демонстрации функциональности</p>
        </footer>
      </div>
    </div>
  );
}
