# Generated by Django 5.2.7 on 2025-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerupgrade',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerupgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
